@api = http://localhost:3020/api/v1/prestamos

# Obtener todos los préstamos
GET {{api}}/pagos/All

###
POST http://localhost:3020/api/v1/prestamos
Content-Type: application/json

{
  "id": 1,
  "clienteId": 1,
  "tipo": "semanal",
  "montoPrestado": 20000,
  "tasaInteres": 0.1,
  "montoInteres": 2000,
  "montoTotal": 22000,
  "saldoRestante": 22000,
  "totalPagos": 14,
  "pagosRealizados": 0,
  "status": "activo",
  "fechaInicio": "2025-01-06T00:00:00Z"
}

###
POST http://localhost:3020/api/v1/prestamos
Content-Type: application/json

{
  "clienteId": 1,
  "tipo": "mensual",
  "montoPrestado": 150000,
  "tasaInteres": 0.1,
  "montoInteres": 1500,
  "montoTotal": 16500,
  "saldoRestante": 16500,
  "totalPagos": 12,
  "pagosRealizados": 0,
  "status": "activo",
  "fechaInicio": "2025-01-06T00:00:00Z"
}
###

POST http://localhost:3020/api/v1/prestamos/2/pagos
Content-Type: application/json

{
  "monto": 1500,
  "fecha": "2025-01-14T00:00:00Z"
}


###
POST http://localhost:3020/api/v1/prestamos/2/pagos
Content-Type: application/json

{
  "monto": 16500,
  "fecha": "2025-01-14T00:00:00Z"
}




###
DELETE http://localhost:3020/api/v1/prestamos/5

###
GET {{api}}/pagos/cliente/1
###
GET http://localhost:3020/api/v1/prestamos/pagos/cliente/1
###
GET {{api}}/pagos/prestamo/1
###
# Obtener el resumen de los préstamos (capital y ganancia)
GET {{api}}/resumen/prestamos
###
GET http://localhost:3020/api/v1/prestamos/pagos/cliente/1/prestamo/1
GET http://localhost:3020/api/v1/prestamos/prestamos/pagos/cliente/1/prestamo/1
