@api = http://localhost:3020/api/v1/users

### Registrar un nuevo usuario
POST {{api}}/register
Content-Type: application/json

{
  "nombre": "Lupita",
  "apellidos": "Bernal Gonzalez",
  "email": "Lupita.2084@gmail.com",
  "password": "Chelito0000"
}

###

### Iniciar sesión con el usuario registrado
POST {{api}}/login
Content-Type: application/json

{
  "email": "AxsandovalBe@ittepic.edu.mx",
  "password": "sABA020401HNENRXA3"
}

###

### Obtener información del usuario actual
GET {{api}}/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzhlYzAyODc4ZDkxNGZiYTFiMzAxMzkiLCJlbWFpbCI6IkF4c2FuZG92YWxCZUBpdHRlcGljLmVkdS5teCIsImlhdCI6MTczNzQ5MjUwMiwiZXhwIjoxNzM3NDk2MTAyfQ.b--fjfUqzJBKLUWDxht40PFCLj78jkXhEPgn-kWoqIc