@api = https://prestamos-h874.onrender.com/api/v1

### Registrar un nuevo usuario
POST {{api}}/register
Content-Type: application/json

{
  "nombre": "Lupita",
  "apellidos": "Bernal Gonzalez",
  "email": "Lupita.2085@gmail.com",
  "password": "Chelito0000"
}

###

### Iniciar sesión con el usuario registrado
POST {{api}}/users/login
Content-Type: application/json

{
  "email": "AxsandovalBe@ittepic.edu.mx",
  "password": "sABA020401HNENRXA3."
}

###

### Obtener información del usuario actual
GET {{api}}/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzhlYzAyODc4ZDkxNGZiYTFiMzAxMzkiLCJlbWFpbCI6IkF4c2FuZG92YWxCZUBpdHRlcGljLmVkdS5teCIsImlhdCI6MTczNzY1OTQxOCwiZXhwIjoxNzM3NjYzMDE4fQ.sjmyXi3jGyWfkZ2ibyyZj6r5vAee0ZKoe0Bj7na4HWM
###Cerrar sesion
POST {{api}}/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzhlYzAyODc4ZDkxNGZiYTFiMzAxMzkiLCJlbWFpbCI6IkF4c2FuZG92YWxCZUBpdHRlcGljLmVkdS5teCIsImlhdCI6MTczNzY1OTQxOCwiZXhwIjoxNzM3NjYzMDE4fQ.sjmyXi3jGyWfkZ2ibyyZj6r5vAee0ZKoe0Bj7na4HWM
Content-Type: application/json


